In [1]:
import cv2
import imutils
import numpy as np
import pandas as pd

In [2]:
img1 = cv2.imread("img1.jpg")
print("Shape : ",img1.shape)
print(img1)

Shape :  (628, 498, 3)
[[[  7  38  23]
  [136 170 160]
  [215 252 250]
  ...
  [ 52  37  35]
  [ 67  48  33]
  [ 62  43  28]]

 [[  8  39  30]
  [136 170 164]
  [213 248 251]
  ...
  [ 54  39  37]
  [ 63  46  33]
  [ 59  42  29]]

 [[  4  36  35]
  [128 163 167]
  [208 244 254]
  ...
  [ 56  41  39]
  [ 57  42  33]
  [ 55  40  31]]

 ...

 [[128 188 254]
  [117 184 253]
  [104 180 255]
  ...
  [ 63  48  46]
  [ 62  48  42]
  [ 71  59  53]]

 [[123 184 252]
  [102 171 241]
  [ 86 164 241]
  ...
  [ 70  55  53]
  [ 63  49  43]
  [ 72  60  54]]

 [[117 182 251]
  [ 91 160 233]
  [ 73 152 231]
  ...
  [ 74  59  57]
  [ 63  49  43]
  [ 72  60  54]]]


In [3]:
img2 = cv2.imread("img2.jpg")
print("Shape : ",img2.shape)
print(img2)

Shape :  (628, 499, 3)
[[[  9  26  23]
  [126 147 148]
  [217 246 250]
  ...
  [ 57  42  40]
  [ 56  41  39]
  [ 54  39  37]]

 [[ 31  51  52]
  [126 151 153]
  [216 248 254]
  ...
  [ 57  42  40]
  [ 55  40  38]
  [ 54  39  37]]

 [[ 21  45  51]
  [116 145 154]
  [198 233 246]
  ...
  [ 56  41  39]
  [ 55  40  38]
  [ 54  39  37]]

 ...

 [[155 189 232]
  [142 190 242]
  [114 184 251]
  ...
  [ 68  53  51]
  [ 69  54  52]
  [ 71  56  54]]

 [[144 182 224]
  [127 177 229]
  [101 172 240]
  ...
  [ 67  52  50]
  [ 68  53  51]
  [ 70  55  53]]

 [[137 177 219]
  [115 170 221]
  [ 89 164 232]
  ...
  [ 66  51  49]
  [ 67  52  50]
  [ 69  54  52]]]


In [4]:
print("Image-1 : ",img1[0][2])
print("Image-2 : ",img2[0][2])

Image-1 :  [215 252 250]
Image-2 :  [217 246 250]


In [5]:
def compare_images(img1, img2):
    dict1 = {}
    for i in range(img1.shape[0]):
        for j in range(img1.shape[1]):
                if not np.array_equal(img1[i][j], img2[i][j]):
                    index = (i,j)
                    value = img2[i][j]
                    dict1[index] = value
    return dict1

hash_dict = compare_images(img1, img2)

In [6]:
hash_dict
df = pd.DataFrame(list(hash_dict.items()), columns=['Index', 'image-2 pixel'])

In [7]:
df.head()

Index    image-2 pixel
0  (0, 0)      [9, 26, 23]
1  (0, 1)  [126, 147, 148]
2  (0, 2)  [217, 246, 250]
3  (0, 3)  [210, 249, 255]
4  (0, 4)  [192, 241, 251]